import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const adminNavigationConfig: NavigationTree[] = [
    {
        key: 'admin.platform',
        path: '',
        title: 'Platform',
        translateKey: 'nav.admin.platform',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.dashboard',
        path: '/admin',
        title: 'Overview',
        translateKey: 'nav.admin.overview',
        icon: 'adminOverview',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.users',
        path: '/admin/users',
        title: 'Users',
        translateKey: 'nav.admin.users',
        icon: 'adminUsers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.businesses',
        path: '/admin/businesses',
        title: 'Businesses',
        translateKey: 'nav.admin.businesses',
        icon: 'adminBusinesses',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.categories',
        path: '/admin/categories',
        title: 'Categories',
        translateKey: 'nav.admin.categories',
        icon: 'adminCategories',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.reports',
        path: '/admin/reports',
        title: 'Reports',
        translateKey: 'nav.admin.reports',
        icon: 'adminReports',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.activity',
        path: '/admin/activity',
        title: 'Activity Log',
        translateKey: 'nav.admin.activity',
        icon: 'adminActivity',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.system',
        path: '',
        title: 'System',
        translateKey: 'nav.admin.system',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.settings',
        path: '/admin/settings',
        title: 'Settings',
        translateKey: 'nav.admin.settings',
        icon: 'adminSettings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.team',
        path: '/admin/team',
        title: 'Admin Team',
        translateKey: 'nav.admin.team',
        icon: 'adminTeam',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'admin.audit',
        path: '/admin/audit',
        title: 'Audit',
        translateKey: 'nav.admin.audit',
        icon: 'adminAudit',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
]

export default adminNavigationConfig
